export const Users = [
  {
    id: 1,
    profilePicture: "https://r2.easyimg.io/0x24yvc97/1.jpeg",
    username: "Fiaona Fussi",
  },
  {
    id: 2,
    profilePicture: "https://r2.easyimg.io/jkmu87rlz/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture:
      "https://r2.easyimg.io/acxfc8w4y/john-wicks-noble-hobby-revealed-keanu-reeves-says-it-was-cut-from-original-film.jpg",
    username: "John Wick",
  },
  {
    id: 4,
    profilePicture: "https://r2.easyimg.io/03ftr8khg/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "https://r2.easyimg.io/phrj8gm0x/5.jpeg",
    username: "Clara Madison",
  },
  {
    id: 6,
    profilePicture: "https://r2.easyimg.io/lbfdnufx2/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "https://r2.easyimg.io/jem9naf88/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "https://r2.easyimg.io/gop8phplb/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "https://r2.easyimg.io/lhp7o6v9k/9.jpeg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "https://r2.easyimg.io/91zsxei3v/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Post = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://r2.easyimg.io/qcryi7s8i/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Keep a habit of chasing time not wasting it",
    photo: "https://r2.easyimg.io/u9fy0cay4/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://r2.easyimg.io/0w0i2646z/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://r2.easyimg.io/bdgle6jhu/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://r2.easyimg.io/lzy3rq1rz/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://r2.easyimg.io/5ywqpdx9a/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://r2.easyimg.io/xcdkfmnio/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "Post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "Post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "Post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
